name: movie_proj
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  firebase_core: ^2.21.0
  firebase_core_web: ^2.8.1
  shared_preferences: ^2.2.2
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  firebase_auth: ^4.12.1
  firebase_auth_web: ^5.8.6
  cloud_firestore: ^4.12.2
  connectivity_plus: ^6.1.4
  rxdart: ^0.27.7
  intl: ^0.18.1
  meta: ^1.9.1
  http: ^1.4.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
